### ISSUE TITLE
Activate Account Button Inoperable on Full Screen

### ISSUE THREAD

**Issue by aarontitus** [CrisisCleanup/crisiscleanup-4-web#211] opened 2023-03-28 06:31 UTC
Just found a really weird error on the Activate Account page. When you maximize the screen, some sort of invisible element overlays the "Activate Account" button, rendering it unreachable and inoperable. However, when you un-maximize the screen (in both Firefox and Chrome), then the "Activate Account" button suddenly works. See mp4 below.

https://user-images.githubusercontent.com/4184619/228147956-58f57d20-0332-4dd2-875a-1fbb0e2bb53a.mp4

**Comment by deepanchal** [comment] 2023-03-30 13:26
Duplicate of #212 
Already fixed by #213

**Closed by deepanchal** 2023-03-30 13:26 UTC
